export const companies = [
  {
    name: "Skyeng",
    jobs: 10,
    subscribers: 173,
    isVerified: true,
    url: "skyeng.com ",
    contact: "100-999",
    address: "Seoul, S.Korea",
  },
  {
    name: "Kappa London",
    jobs: 7,
    subscribers: 61,
    isVerified: false,
    url: "kappa-london.com ",
    contact: "100-678",
    address: "Seoul, S.Korea",
  },
  {
    name: "Deep Consulting Solutions",
    jobs: 21,
    subscribers: 224,
    isVerified: true,
    url: "Deep-Consulting.com ",
    contact: "100-678",
    address: "Seoul, S.Korea",
  },
  {
    name: "Pragmateem",
    jobs: 2,
    subscribers: 13,
    isVerified: false,
    url: "Pragmateem.com ",
    contact: "100-765",
    address: "Seoul, S.Korea",
  },
  {
    name: "Kepler Co., Ltd.",
    jobs: 23,
    subscribers: 402,
    isVerified: true,
    url: "Kepler.com ",
    contact: "100-333",
    address: "Seoul, S.Korea",
  },
  {
    name: "NEKOM CC Gmbh",
    jobs: 0,
    subscribers: 0,
    isVerified: false,
    url: "nekom.com ",
    contact: "100-777",
    address: "Seoul, S.Korea",
  },
  {
    name: "Hotjar",
    jobs: 2,
    subscribers: 5,
    isVerified: true,
    url: "hotjar.com ",
    contact: "100-999",
    address: "Seoul, S.Korea",
  },
  {
    name: "The Difference Engine",
    jobs: 0,
    subscribers: 3,
    isVerified: false,
    url: "Engine.com ",
    contact: "100-111",
    address: "Seoul, S.Korea",
  },
];
