export const Contents = [
  {
    
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },

  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Intermediate",
    pay: "$25-$30/hr",
    applyLink: "/",
  },

  {
    title: "Product Designer",
    description:
      "KeplerLab is a VC-backed, stealth, application-only platform for senior product designers to team up with the best companies on their next big thing.",
    timePosted: "30mins ago",
    company: "KeplerLab",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "UI/UX Designer",
    description:
      "We’re looking for an experienced and talented UI designer to design and shape unique, user-centric design systems and experiences.",
    timePosted: "45mins ago",
    company: "KeplerLab",
    jobType: "Part-Time",
    level: "Expert",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
  {
    title: "Senior Python Developer",
    description:
      "The ideal candidate will be responsible for helping us develop a wide variety of projects leveraging PostgreSQL, Django, and Python.",
    timePosted: "1hr ago",
    company: "Infosys",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$20/hr",
    applyLink: "/",
  },
  {
    title: "Junior DevOps Engineer",
    description: "We need one to Work with fellow DevOps engineers.",
    timePosted: "2hrs ago",
    company: "N9 IT SOLUTIONS",
    jobType: "Full-Time",
    level: "Senior",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Quality Specialist",
    description:
      "iGaming company looking for QA Engineer to be based in Malta or Remotely in Europe.",
    timePosted: "3hr ago",
    company: "Pentasia",
    jobType: "Full-Time",
    level: "Intermediate",
    pay: "$15/hr",
    applyLink: "/",
  },
  {
    title: "Web Developer",
    description:
      "Entrust is seeking a Sitecore developer that will perform the accountabilities detailed below and other duties as assigned.",
    timePosted: "2hrs ago",
    company: "Entrust Datacard",
    jobType: "Part-Time",
    level: "Lead",
    pay: "$25-$30/hr",
    applyLink: "/",
  },
];
